[gemini-assistant-overlay]
description=Gemini Floating Assistant Overlay
above=true
aboverule=3
noborder=true
noborderrule=3
position=1490,330
positionrule=3
size=410,710
sizerule=3
skiptaskbar=true
skiptaskbarrule=3
skipswitcher=true
skipswitcherrule=3
wmclass=brave-gemini.google.com__app-Default
wmclassmatch=1
